import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import profileRouter from "./profile";
import chatRouter from "./chat";
import parentRouter from "./parent";
import gamesRouter from "./games";
import assessmentRouter from "./assessment";
import curriculumRouter from "./curriculum";
import gamificationRouter from "./gamification";
import notificationsRouter from "./notifications";
import tutorRouter from "./tutor";
import goalsRouter from "./goals";
import worksheetRouter from "./worksheet";
import bookmarksRouter from "./bookmarks";
import messagesRouter from "./messages";
import feesRouter from "./fees";
import reportCardRouter from "./reportCard";
import attendanceRouter from "./attendance";
import mockExamRouter from "./mockExam";
import duelsRouter from "./duels";
import meetingsRouter from "./meetings";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(profileRouter);
router.use(chatRouter);
router.use(parentRouter);
router.use(gamesRouter);
router.use(assessmentRouter);
router.use(curriculumRouter);
router.use(gamificationRouter);
router.use(notificationsRouter);
router.use(tutorRouter);
router.use(goalsRouter);
router.use(worksheetRouter);
router.use(bookmarksRouter);
router.use(messagesRouter);
router.use(feesRouter);
router.use(reportCardRouter);
router.use(attendanceRouter);
router.use(mockExamRouter);
router.use(duelsRouter);
router.use(meetingsRouter);

export default router;
